dubug: remove debug code

diff --git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml
--- a/.github/workflows/ruby.yml
+++ b/.github/workflows/ruby.yml
@@ -171,82 +171,82 @@ jobs:
           path: "ruby/pkg/"
       - run: apk add --no-cache g++ musl-dev make git chromium chromium-chromedriver xvfb xvfb-run
         working-directory: ruby
-      - run: gem install pkg/gems/eyes_universal-*.gem --verbose
+      - run: gem install pkg/gems/eyes_universal-*.gem
         working-directory: ruby
       - run: bundle install
         working-directory: ruby
-      - run: gem env
-        working-directory: ruby
-      - run: rm pkg/gems/eyes_universal-*.gem
-        working-directory: ruby
+#      - run: gem env
+#        working-directory: ruby
+#      - run: rm pkg/gems/eyes_universal-*.gem
+#        working-directory: ruby
       - run: xvfb-run bundle exec rspec spec/version/simple_spec.rb
         working-directory: ruby
 
-#  unit-test:
-#    needs: dist-build
-#    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.basic-tests }}
-#    strategy:
-#      matrix:
-#        os: [ ubuntu-latest ]
-#        ruby-version: ['2.6', '2.7', '3.0', '3.1']
-#    runs-on: ${{ matrix.os }}
-#    env:
-#      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
-#
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          ref: ${{inputs.ref || github.ref}}
-#      - name: Set up Ruby
-#        uses: ruby/setup-ruby@v1
-#        with:
-#          ruby-version: ${{ matrix.ruby-version }}
-#      - name: Load gems
-#        uses: actions/download-artifact@v3
-#        with:
-#          name: gems
-#          path: "ruby/pkg/"
-#      - name: Run tests
-#        env:
-#          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
-#        working-directory: ruby
-#        run: |
-#          gem install pkg/gems/eyes_universal-*.gem
-#          bundle install
-#          bundle exec rake github:unit_tests
-#
-#  visual-test:
-#    needs: dist-build
-#    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.basic-tests }}
-#    strategy:
-#      matrix:
-#        os: [ ubuntu-latest ]
-#        ruby-version: ['2.6', '2.7', '3.0', '3.1']
-#    runs-on: ${{ matrix.os }}
-#    env:
-#      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
-#
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          ref: ${{inputs.ref || github.ref}}
-#      - name: Set up Ruby
-#        uses: ruby/setup-ruby@v1
-#        with:
-#          ruby-version: ${{ matrix.ruby-version }}
-#      - name: Load gems
-#        uses: actions/download-artifact@v3
-#        with:
-#          name: gems
-#          path: "ruby/pkg/"
-#      - name: Run visual tests
-#        env:
-#          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
-#        working-directory: ruby
-#        run: |
-#          gem install pkg/gems/eyes_universal-*.gem
-#          bundle install
-#          bundle exec rake github:vg_tests
+  unit-test:
+    needs: dist-build
+    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.basic-tests }}
+    strategy:
+      matrix:
+        os: [ ubuntu-latest ]
+        ruby-version: ['2.6', '2.7', '3.0', '3.1']
+    runs-on: ${{ matrix.os }}
+    env:
+      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{inputs.ref || github.ref}}
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: ${{ matrix.ruby-version }}
+      - name: Load gems
+        uses: actions/download-artifact@v3
+        with:
+          name: gems
+          path: "ruby/pkg/"
+      - name: Run tests
+        env:
+          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
+        working-directory: ruby
+        run: |
+          gem install pkg/gems/eyes_universal-*.gem
+          bundle install
+          bundle exec rake github:unit_tests
+
+  visual-test:
+    needs: dist-build
+    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.basic-tests }}
+    strategy:
+      matrix:
+        os: [ ubuntu-latest ]
+        ruby-version: ['2.6', '2.7', '3.0', '3.1']
+    runs-on: ${{ matrix.os }}
+    env:
+      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{inputs.ref || github.ref}}
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: ${{ matrix.ruby-version }}
+      - name: Load gems
+        uses: actions/download-artifact@v3
+        with:
+          name: gems
+          path: "ruby/pkg/"
+      - name: Run visual tests
+        env:
+          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
+        working-directory: ruby
+        run: |
+          gem install pkg/gems/eyes_universal-*.gem
+          bundle install
+          bundle exec rake github:vg_tests
 
 #  appium-test:
 #    needs: dist-build
@@ -282,132 +282,132 @@ jobs:
 #          bundle install
 #          bundle exec rake github:appium_tests
 
-#  universal-server-test:
-#    needs: dist-build
-#    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.basic-tests }}
-#    strategy:
-#      matrix:
-#        os: [ ubuntu-latest, macos-latest, windows-latest ]
-#        ruby-version: ['2.6', '2.7', '3.0', '3.1']
-#    runs-on: ${{ matrix.os }}
-#
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          ref: ${{inputs.ref || github.ref}}
-#      - name: Set up Ruby
-#        uses: ruby/setup-ruby@v1
-#        with:
-#          ruby-version: ${{ matrix.ruby-version }}
-#      - uses: actions/setup-python@v3
-#        with:
-#          python-version: "3.10"
-#      - name: Load gems
-#        uses: actions/download-artifact@v3
-#        with:
-#          name: gems
-#          path: "ruby/pkg/"
-#      - name: Run Server tests
-#        env:
-#          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
-#        working-directory: ruby
-#        run: |
-#          gem install pkg/gems/eyes_universal-*.gem
-#          bundle install
-#          bundle exec rake github:server_tests
-#          pip install pytest psutil
-#          pytest -vv spec/universal_server/universal_bindings_termination_test.py
-#
-#  generic-test:
-#    needs: dist-build
-#    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.generic-tests }}
-#    runs-on: ubuntu-latest
-#    env:
-#      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
-#      APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}
-#      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
-#      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
-#      DISPLAY: ':99'
-#
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          ref: ${{inputs.ref || github.ref}}
-#      - name: Set up Ruby
-#        uses: ruby/setup-ruby@v1
-#        with:
-#          ruby-version: '2.6'
-#      - name: Load gems
-#        uses: actions/download-artifact@v3
-#        with:
-#          name: gems
-#          path: "ruby/pkg/"
-#      - name: Setup xvfb
-#        working-directory: ruby
-#        run: |
-#          sudo apt-get install -y xvfb
-#          Xvfb -ac $DISPLAY -screen 0 1280x1024x16 &
-#      - name: Run tests
-#        working-directory: ruby
-#        env:
-#          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
-#        run: |
-#          gem install pkg/gems/eyes_universal-*.gem
-#          bundle install
-#          chmod +x ./generic_tests.sh && ./generic_tests.sh
-#
-#  tag-only:
-#    needs:
-#      - platform-test
-#      - alpine-test
-#      - unit-test
-#      - visual-test
-##      - appium-test
-#      - universal-server-test
-#      - generic-test
-#    runs-on: ubuntu-latest
-#    if: github.ref_type == 'tag' && startsWith(github.ref_name, '@applitools/ruby/eyes_selenium')
-#    env:
-#      ALLOWED_RUBY_RELEASE_COMMITERS: ${{ secrets.ALLOWED_RUBY_RELEASE_COMMITERS }}
-#      TEST_REPORT_SANDBOX: False
-#
-#    steps:
-#      - uses: actions/checkout@v3
-#        with:
-#          ref: ${{inputs.ref || github.ref}}
-#      - name: ChangeLog check
-#        working-directory: ruby
-#        run: |
-#          export GITHUB_TAG_VERSION=${{ github.ref_name }}
-#          export TAG_VERSION="${GITHUB_TAG_VERSION}"
-#          echo $TAG_VERSION
-#          if [[ ! ($TAG_VERSION =~ ^@applitools/ruby/eyes_selenium@[0-9]+\.[0-9]+\.[0-9]+(\.[0-9a-z]+)?$) ]]; then
-#            echo 'Tag Version check Failed'
-#            exit 1
-#          fi
-#          export SDK_VERSION=$(echo $GITHUB_TAG_VERSION | sed 's/@applitools\/ruby\/eyes_selenium@[^.0-9a-z]*//g')
-#          echo $SDK_VERSION
-#
-#          export TMP_CHANGELOG=$(bash ./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md")
-#          export CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "There is no change log for version $SDK_VERSION"; echo "$TMP_CHANGELOG")
-#
-#          echo $CHANGELOG
-#          echo $TMP_CHANGELOG
-#
-#          if [[ (-z "$TMP_CHANGELOG") ]]; then
-#            echo "THE CHANGELOG IS NOT CORRECT"
-#            exit 1
-#          fi
-#
-#          COMMITTER_EMAIL="$(git log -1 ${{ github.sha }} --pretty="%cE")"
-#
-#          if [[ ("$ALLOWED_RUBY_RELEASE_COMMITERS" =~ .*"$COMMITTER_EMAIL".*) && $TMP_CHANGELOG ]]; then
-#            echo "DEPLOY";
-#            SDK='ruby'
-#            TEST_COVERAGE_GAP=$(cat testCoverageGap.txt);
-#            bash ./sendMail.sh "$SDK" "$TAG_VERSION" "$CHANGELOG" "$TEST_COVERAGE_GAP";
-#            echo "DEPLOY SUCCESSFUL";
-#          else
-#            echo "DEPLOYMENT FAILED";
-#            exit 1;
-#          fi
+  universal-server-test:
+    needs: dist-build
+    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.basic-tests }}
+    strategy:
+      matrix:
+        os: [ ubuntu-latest, macos-latest, windows-latest ]
+        ruby-version: ['2.6', '2.7', '3.0', '3.1']
+    runs-on: ${{ matrix.os }}
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{inputs.ref || github.ref}}
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: ${{ matrix.ruby-version }}
+      - uses: actions/setup-python@v3
+        with:
+          python-version: "3.10"
+      - name: Load gems
+        uses: actions/download-artifact@v3
+        with:
+          name: gems
+          path: "ruby/pkg/"
+      - name: Run Server tests
+        env:
+          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
+        working-directory: ruby
+        run: |
+          gem install pkg/gems/eyes_universal-*.gem
+          bundle install
+          bundle exec rake github:server_tests
+          pip install pytest psutil
+          pytest -vv spec/universal_server/universal_bindings_termination_test.py
+
+  generic-test:
+    needs: dist-build
+    if: ${{ !(github.event_name == 'workflow_dispatch') || inputs.generic-tests }}
+    runs-on: ubuntu-latest
+    env:
+      APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
+      APPLITOOLS_API_KEY_READ: ${{ secrets.APPLITOOLS_API_KEY_READ }}
+      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
+      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
+      DISPLAY: ':99'
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{inputs.ref || github.ref}}
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: '2.6'
+      - name: Load gems
+        uses: actions/download-artifact@v3
+        with:
+          name: gems
+          path: "ruby/pkg/"
+      - name: Setup xvfb
+        working-directory: ruby
+        run: |
+          sudo apt-get install -y xvfb
+          Xvfb -ac $DISPLAY -screen 0 1280x1024x16 &
+      - name: Run tests
+        working-directory: ruby
+        env:
+          BUNDLE_GEMFILE: ${{ github.workspace }}/ruby/GemfileGithub
+        run: |
+          gem install pkg/gems/eyes_universal-*.gem
+          bundle install
+          chmod +x ./generic_tests.sh && ./generic_tests.sh
+
+  tag-only:
+    needs:
+      - platform-test
+      - alpine-test
+      - unit-test
+      - visual-test
+#      - appium-test
+      - universal-server-test
+      - generic-test
+    runs-on: ubuntu-latest
+    if: github.ref_type == 'tag' && startsWith(github.ref_name, '@applitools/ruby/eyes_selenium')
+    env:
+      ALLOWED_RUBY_RELEASE_COMMITERS: ${{ secrets.ALLOWED_RUBY_RELEASE_COMMITERS }}
+      TEST_REPORT_SANDBOX: False
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{inputs.ref || github.ref}}
+      - name: ChangeLog check
+        working-directory: ruby
+        run: |
+          export GITHUB_TAG_VERSION=${{ github.ref_name }}
+          export TAG_VERSION="${GITHUB_TAG_VERSION}"
+          echo $TAG_VERSION
+          if [[ ! ($TAG_VERSION =~ ^@applitools/ruby/eyes_selenium@[0-9]+\.[0-9]+\.[0-9]+(\.[0-9a-z]+)?$) ]]; then
+            echo 'Tag Version check Failed'
+            exit 1
+          fi
+          export SDK_VERSION=$(echo $GITHUB_TAG_VERSION | sed 's/@applitools\/ruby\/eyes_selenium@[^.0-9a-z]*//g')
+          echo $SDK_VERSION
+
+          export TMP_CHANGELOG=$(bash ./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md")
+          export CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "There is no change log for version $SDK_VERSION"; echo "$TMP_CHANGELOG")
+
+          echo $CHANGELOG
+          echo $TMP_CHANGELOG
+
+          if [[ (-z "$TMP_CHANGELOG") ]]; then
+            echo "THE CHANGELOG IS NOT CORRECT"
+            exit 1
+          fi
+
+          COMMITTER_EMAIL="$(git log -1 ${{ github.sha }} --pretty="%cE")"
+
+          if [[ ("$ALLOWED_RUBY_RELEASE_COMMITERS" =~ .*"$COMMITTER_EMAIL".*) && $TMP_CHANGELOG ]]; then
+            echo "DEPLOY";
+            SDK='ruby'
+            TEST_COVERAGE_GAP=$(cat testCoverageGap.txt);
+            bash ./sendMail.sh "$SDK" "$TAG_VERSION" "$CHANGELOG" "$TEST_COVERAGE_GAP";
+            echo "DEPLOY SUCCESSFUL";
+          else
+            echo "DEPLOYMENT FAILED";
+            exit 1;
+          fi
